-- Consolidated baseline (ember-postgress-migration follow-up, 2026-08-24): replaces the
-- non-reproducible "V1" this project carried until now (a virtual marker meaning "whatever
-- ddl-auto had built before Flyway existed here" -- never captured as a runnable script).
-- V2 through V15 assumed that pre-existing schema and mostly ALTER it; none of them are able
-- to CREATE it from nothing. Confirmed the hard way on 2026-08-24: a truly empty Postgres
-- (exactly what every fresh Vanter Hub install starts from) cannot bootstrap through this
-- project's migration history as it stood.
--
-- This file is a `pg_dump --schema-only` of the fully-migrated schema (through V15),
-- with two things removed and one thing added:
--   - The `flyway_schema_history` table/constraint/index: Flyway creates and owns that table
--     itself: it must never be defined by a migration.
--   - The `\restrict`/`\unrestrict` psql meta-commands pg_dump 16.1+ emits: those aren't SQL,
--     Flyway's JDBC executor can't run them.
--   - The V4 seed row for `platform_operators` (email `platform-admin@ember.local`, password
--     `ChangeMe123!`, same as V4 always shipped) — a schema-only dump carries no data, and
--     without this a fresh install would have zero way to log into `/console`.
--
-- Known cosmetic drift from the original hand-authored V2-V15: this dump was taken against a
-- schema rebuilt via `ddl-auto=create` (see PROGRESS.md's postgres-migration recovery note),
-- so a few constraints that early migrations named explicitly now carry Hibernate's default
-- generated names instead (e.g. `uk_platform_operators_email` -> `platform_operators_email_key`).
-- Purely cosmetic -- the constraints themselves are identical -- but a future migration that
-- tries to `DROP CONSTRAINT` one of these by its old hand-picked name will need to check its
-- actual current name first.
--
-- V2 through V15's original files are preserved for their historical/explanatory value at
-- `backend/src/main/resources/db/migration-archive/` (outside Flyway's scanned
-- `classpath:db/migration`, so they're never re-applied) rather than deleted.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bill_splits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bill_splits (
    amount numeric(10,2) NOT NULL,
    bill_id bigint NOT NULL,
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    participant_name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT bill_splits_status_check CHECK (((status)::text = ANY ((ARRAY['UNPAID'::character varying, 'PARTIALLY_PAID'::character varying, 'PAID'::character varying])::text[])))
);


--
-- Name: bill_splits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bill_splits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bill_splits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bills (
    total numeric(10,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    voided_at timestamp(6) without time zone,
    tenant_id uuid NOT NULL,
    session_id character varying(255) NOT NULL,
    split_method character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    void_reason character varying(255),
    voided_by character varying(255),
    CONSTRAINT bills_split_method_check CHECK (((split_method)::text = ANY ((ARRAY['BY_CONSUMPTION'::character varying, 'EQUAL_PARTS'::character varying])::text[]))),
    CONSTRAINT bills_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'PAID'::character varying, 'VOIDED'::character varying])::text[])))
);


--
-- Name: bills_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cash_movements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cash_movements (
    amount numeric(10,2) NOT NULL,
    cash_shift_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    created_by character varying(255) NOT NULL,
    reason character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT cash_movements_type_check CHECK (((type)::text = ANY ((ARRAY['CASH_IN'::character varying, 'CASH_OUT'::character varying])::text[])))
);


--
-- Name: cash_movements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cash_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cash_shifts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cash_shifts (
    counted_cash numeric(10,2),
    expected_cash numeric(10,2),
    opening_float numeric(10,2) NOT NULL,
    shift_number integer NOT NULL,
    total_cash_in numeric(10,2),
    total_cash_out numeric(10,2),
    total_cash_sales numeric(10,2),
    total_digital_sales numeric(10,2),
    variance numeric(10,2),
    closed_at timestamp(6) without time zone,
    id bigint NOT NULL,
    opened_at timestamp(6) without time zone NOT NULL,
    tenant_id uuid NOT NULL,
    closed_by character varying(255),
    opened_by character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT cash_shifts_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: cash_shifts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cash_shifts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_shifts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    description character varying(255),
    img_url character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dining_table; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dining_table (
    is_active boolean NOT NULL,
    table_number integer NOT NULL,
    id uuid NOT NULL,
    restaurant_id uuid NOT NULL
);



--
-- Name: inventory_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_items (
    current_stock numeric(10,3) NOT NULL,
    low_stock_threshold numeric(10,3) NOT NULL,
    id bigint NOT NULL,
    menu_item_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    tenant_id uuid NOT NULL,
    unit character varying(20) NOT NULL
);


--
-- Name: inventory_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kitchen_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kitchen_orders (
    active boolean NOT NULL,
    table_number integer NOT NULL,
    created_at timestamp(6) without time zone,
    tenant_id uuid NOT NULL,
    id character varying(36) NOT NULL,
    session_id character varying(255) NOT NULL,
    items jsonb NOT NULL
);


--
-- Name: loyalty_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.loyalty_accounts (
    total_points integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    user_id character varying(255) NOT NULL
);


--
-- Name: loyalty_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.loyalty_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loyalty_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: loyalty_rewards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.loyalty_rewards (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    required_tier character varying(255) NOT NULL,
    CONSTRAINT loyalty_rewards_required_tier_check CHECK (((required_tier)::text = ANY ((ARRAY['BRONCE'::character varying, 'PLATA'::character varying, 'ORO'::character varying, 'PLATINO'::character varying])::text[])))
);


--
-- Name: loyalty_rewards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.loyalty_rewards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loyalty_rewards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: loyalty_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.loyalty_transactions (
    amount numeric(10,2),
    points integer NOT NULL,
    bill_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    loyalty_account_id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    reason character varying(255) NOT NULL
);


--
-- Name: loyalty_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.loyalty_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loyalty_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_item_modifier_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_item_modifier_groups (
    display_order integer NOT NULL,
    group_id bigint NOT NULL,
    id bigint NOT NULL,
    menu_item_id bigint NOT NULL
);


--
-- Name: menu_item_modifier_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_item_modifier_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_item_modifier_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_items (
    available boolean NOT NULL,
    price numeric(10,2) NOT NULL,
    category_id bigint NOT NULL,
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    description character varying(255),
    image_url character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: menu_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modifier_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.modifier_groups (
    active boolean NOT NULL,
    max_selections integer,
    min_selections integer NOT NULL,
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    selection_type character varying(255) NOT NULL,
    CONSTRAINT modifier_groups_selection_type_check CHECK (((selection_type)::text = ANY ((ARRAY['SINGLE_REQUIRED'::character varying, 'MULTI_OPTIONAL'::character varying, 'MULTI_LIMITED'::character varying])::text[])))
);


--
-- Name: modifier_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.modifier_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modifier_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modifier_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.modifier_options (
    active boolean NOT NULL,
    display_order integer NOT NULL,
    price_delta numeric(10,2) NOT NULL,
    group_id bigint NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: modifier_options_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.modifier_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modifier_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    amount numeric(10,2) NOT NULL,
    bill_id bigint NOT NULL,
    cash_shift_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    gateway_ref character varying(255),
    method character varying(255) NOT NULL,
    participant_name character varying(255) NOT NULL,
    processed_by character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['DIGITAL'::character varying, 'PHYSICAL'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: platform_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.platform_audit_log (
    created_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    operator_id uuid NOT NULL,
    restaurant_id uuid,
    action character varying(255) NOT NULL,
    new_value text,
    old_value text,
    operator_email character varying(255) NOT NULL
);


--
-- Name: platform_operators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.platform_operators (
    created_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL
);


--
-- Name: print_agents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.print_agents (
    created_at timestamp(6) without time zone NOT NULL,
    last_seen_at timestamp(6) without time zone,
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    api_key_hash character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT print_agents_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'REVOKED'::character varying])::text[])))
);


--
-- Name: print_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.print_jobs (
    attempts integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    last_error character varying(255),
    payload text NOT NULL,
    role character varying(255) NOT NULL,
    source_id character varying(255) NOT NULL,
    source_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT print_jobs_role_check CHECK (((role)::text = ANY ((ARRAY['KITCHEN'::character varying, 'RECEIPT'::character varying])::text[]))),
    CONSTRAINT print_jobs_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['BILL_RECEIPT'::character varying, 'KITCHEN_TICKET'::character varying])::text[]))),
    CONSTRAINT print_jobs_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'PRINTED'::character varying, 'ERROR'::character varying])::text[])))
);


--
-- Name: printer_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.printer_configs (
    active boolean NOT NULL,
    port integer,
    agent_id uuid NOT NULL,
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    com_port character varying(255),
    connection_type character varying(255) NOT NULL,
    host character varying(255),
    label character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT printer_configs_connection_type_check CHECK (((connection_type)::text = ANY ((ARRAY['NETWORK'::character varying, 'USB'::character varying])::text[]))),
    CONSTRAINT printer_configs_role_check CHECK (((role)::text = ANY ((ARRAY['KITCHEN'::character varying, 'RECEIPT'::character varying])::text[])))
);


--
-- Name: refunds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refunds (
    amount numeric(10,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    payment_id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    reason character varying(255) NOT NULL,
    refunded_by character varying(255) NOT NULL
);


--
-- Name: refunds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refunds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refunds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurant_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.restaurant_settings (
    id uuid NOT NULL,
    restaurant_id uuid NOT NULL,
    payload jsonb
);


--
-- Name: restaurants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.restaurants (
    created_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    currency character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    plan character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    timezone character varying(255) NOT NULL,
    CONSTRAINT restaurants_plan_check CHECK (((plan)::text = ANY ((ARRAY['FREE'::character varying, 'STARTER'::character varying, 'PRO'::character varying, 'ENTERPRISE'::character varying])::text[]))),
    CONSTRAINT restaurants_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'INACTIVE'::character varying])::text[])))
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    max_participants integer NOT NULL,
    created_at timestamp(6) without time zone,
    version bigint,
    join_code character varying(10),
    table_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    status character varying(20) NOT NULL,
    id character varying(36) NOT NULL,
    waiter_id character varying(255),
    activity_log jsonb NOT NULL,
    items jsonb NOT NULL,
    participants jsonb NOT NULL,
    CONSTRAINT sessions_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'BILLING'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    active boolean NOT NULL,
    efficiency_percentage numeric(38,2),
    pending_hours numeric(38,2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    restaurant_id uuid,
    contract_type character varying(255),
    email character varying(255) NOT NULL,
    id character varying(255) NOT NULL,
    job_title character varying(255),
    location character varying(255),
    name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    shift character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'WAITER'::character varying, 'KITCHEN'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: bill_splits bill_splits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bill_splits
    ADD CONSTRAINT bill_splits_pkey PRIMARY KEY (id);


--
-- Name: bills bills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bills
    ADD CONSTRAINT bills_pkey PRIMARY KEY (id);


--
-- Name: cash_movements cash_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cash_movements
    ADD CONSTRAINT cash_movements_pkey PRIMARY KEY (id);


--
-- Name: cash_shifts cash_shifts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cash_shifts
    ADD CONSTRAINT cash_shifts_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: dining_table dining_table_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dining_table
    ADD CONSTRAINT dining_table_pkey PRIMARY KEY (id);




--
-- Name: inventory_items inventory_items_menu_item_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT inventory_items_menu_item_id_key UNIQUE (menu_item_id);


--
-- Name: inventory_items inventory_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT inventory_items_pkey PRIMARY KEY (id);


--
-- Name: kitchen_orders kitchen_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kitchen_orders
    ADD CONSTRAINT kitchen_orders_pkey PRIMARY KEY (id);


--
-- Name: loyalty_accounts loyalty_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loyalty_accounts
    ADD CONSTRAINT loyalty_accounts_pkey PRIMARY KEY (id);


--
-- Name: loyalty_rewards loyalty_rewards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loyalty_rewards
    ADD CONSTRAINT loyalty_rewards_pkey PRIMARY KEY (id);


--
-- Name: loyalty_transactions loyalty_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loyalty_transactions
    ADD CONSTRAINT loyalty_transactions_pkey PRIMARY KEY (id);


--
-- Name: menu_item_modifier_groups menu_item_modifier_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_item_modifier_groups
    ADD CONSTRAINT menu_item_modifier_groups_pkey PRIMARY KEY (id);


--
-- Name: menu_items menu_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_items
    ADD CONSTRAINT menu_items_pkey PRIMARY KEY (id);


--
-- Name: modifier_groups modifier_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modifier_groups
    ADD CONSTRAINT modifier_groups_pkey PRIMARY KEY (id);


--
-- Name: modifier_options modifier_options_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modifier_options
    ADD CONSTRAINT modifier_options_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: platform_audit_log platform_audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_audit_log
    ADD CONSTRAINT platform_audit_log_pkey PRIMARY KEY (id);


--
-- Name: platform_operators platform_operators_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_operators
    ADD CONSTRAINT platform_operators_email_key UNIQUE (email);


--
-- Name: platform_operators platform_operators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_operators
    ADD CONSTRAINT platform_operators_pkey PRIMARY KEY (id);


--
-- Name: print_agents print_agents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.print_agents
    ADD CONSTRAINT print_agents_pkey PRIMARY KEY (id);


--
-- Name: print_jobs print_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.print_jobs
    ADD CONSTRAINT print_jobs_pkey PRIMARY KEY (id);


--
-- Name: printer_configs printer_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.printer_configs
    ADD CONSTRAINT printer_configs_pkey PRIMARY KEY (id);


--
-- Name: refunds refunds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT refunds_pkey PRIMARY KEY (id);


--
-- Name: restaurant_settings restaurant_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurant_settings
    ADD CONSTRAINT restaurant_settings_pkey PRIMARY KEY (id);


--
-- Name: restaurant_settings restaurant_settings_restaurant_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurant_settings
    ADD CONSTRAINT restaurant_settings_restaurant_id_key UNIQUE (restaurant_id);


--
-- Name: restaurants restaurants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT restaurants_pkey PRIMARY KEY (id);


--
-- Name: restaurants restaurants_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT restaurants_slug_key UNIQUE (slug);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: categories uk_categories_tenant_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT uk_categories_tenant_name UNIQUE (tenant_id, name);


--
-- Name: loyalty_accounts uk_loyalty_accounts_tenant_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loyalty_accounts
    ADD CONSTRAINT uk_loyalty_accounts_tenant_user UNIQUE (tenant_id, user_id);


--
-- Name: menu_item_modifier_groups uk_menu_item_modifier_groups; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_item_modifier_groups
    ADD CONSTRAINT uk_menu_item_modifier_groups UNIQUE (menu_item_id, group_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);




--
-- Name: idx_bill_splits_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bill_splits_tenant ON public.bill_splits USING btree (tenant_id);


--
-- Name: idx_cash_movements_shift; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cash_movements_shift ON public.cash_movements USING btree (cash_shift_id);


--
-- Name: idx_dining_table_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dining_table_tenant ON public.dining_table USING btree (restaurant_id);


--
-- Name: idx_inventory_items_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_inventory_items_tenant ON public.inventory_items USING btree (tenant_id);


--
-- Name: idx_kitchen_orders_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kitchen_orders_tenant ON public.kitchen_orders USING btree (tenant_id);


--
-- Name: idx_kitchen_orders_tenant_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kitchen_orders_tenant_active ON public.kitchen_orders USING btree (tenant_id, active);


--
-- Name: idx_kitchen_orders_tenant_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kitchen_orders_tenant_session ON public.kitchen_orders USING btree (tenant_id, session_id);


--
-- Name: idx_loyalty_transactions_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_loyalty_transactions_account ON public.loyalty_transactions USING btree (loyalty_account_id);


--
-- Name: idx_menu_items_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_menu_items_tenant ON public.menu_items USING btree (tenant_id);


--
-- Name: idx_modifier_groups_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_modifier_groups_tenant ON public.modifier_groups USING btree (tenant_id);


--
-- Name: idx_payments_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payments_tenant ON public.payments USING btree (tenant_id);


--
-- Name: idx_refunds_payment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refunds_payment ON public.refunds USING btree (payment_id);


--
-- Name: idx_sessions_join_code_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sessions_join_code_status ON public.sessions USING btree (join_code, status);


--
-- Name: idx_sessions_tenant_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sessions_tenant_status ON public.sessions USING btree (tenant_id, status);


--
-- Name: idx_sessions_tenant_table_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sessions_tenant_table_status ON public.sessions USING btree (tenant_id, table_id, status);


--
-- Name: loyalty_transactions fk429dwg0ieqyqbtnkfb7v9ues3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loyalty_transactions
    ADD CONSTRAINT fk429dwg0ieqyqbtnkfb7v9ues3 FOREIGN KEY (loyalty_account_id) REFERENCES public.loyalty_accounts(id);


--
-- Name: menu_items fk5bg0vbmql5ggu48n7d5pwgjg3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_items
    ADD CONSTRAINT fk5bg0vbmql5ggu48n7d5pwgjg3 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: bill_splits fk5xlgtex1wlc15xtlmofyl1d9x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bill_splits
    ADD CONSTRAINT fk5xlgtex1wlc15xtlmofyl1d9x FOREIGN KEY (bill_id) REFERENCES public.bills(id);


--
-- Name: payments fk9565r6579khpdjxnyla0l2ycd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk9565r6579khpdjxnyla0l2ycd FOREIGN KEY (bill_id) REFERENCES public.bills(id);


--
-- Name: modifier_options fkgo1fcvnt2tsar5co6axsj4dx0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modifier_options
    ADD CONSTRAINT fkgo1fcvnt2tsar5co6axsj4dx0 FOREIGN KEY (group_id) REFERENCES public.modifier_groups(id);


--
-- Name: refunds fkpt9ic0j1y6xwlej99wnynvnpy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT fkpt9ic0j1y6xwlej99wnynvnpy FOREIGN KEY (payment_id) REFERENCES public.payments(id);


--
-- Name: users fksd7jrkn6c8wb1y8ffbdn3krel; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fksd7jrkn6c8wb1y8ffbdn3krel FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);



-- Seed the initial platform operator so the console has a login on a fresh install (same
-- row V4 always shipped -- see V4's own comment for the rotation note). Idempotent.
-- Schema-qualified (public.platform_operators): pg_dump's own header sets search_path to
-- empty, so an unqualified name here (unlike in V4's original context) would not resolve.
INSERT INTO public.platform_operators (id, name, email, password_hash, created_at)
VALUES (
    gen_random_uuid(),
    'Platform Admin',
    'platform-admin@ember.local',
    '$2a$10$yL9cRGZ5peuOyztoRdLQUemp1I0alVCdzOyxmdqhCZAukOlD1a7wC',
    now()
)
ON CONFLICT (email) DO NOTHING;
