package com.vanter.ember.licensing.service;

import com.vanter.ember.hub.license.LicenseKey;
import com.vanter.ember.hub.license.LicenseKeyParser;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.interfaces.RSAPrivateCrtKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.RSAPublicKeySpec;
import java.time.Instant;
import java.util.Base64;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

/**
 * Signs {@code license.key} files for {@code /console}'s "Emitir licencia Hub" action and
 * verifies them again for {@code /hub-activations} — both directions share one key pair, so this
 * is the single source of truth for it. The public half is derived from the private key at
 * startup (RSA private keys generated by Java's default provider are CRT keys, which expose the
 * modulus/public exponent needed to reconstruct the public key) — no separate public key config
 * to keep in sync. The corresponding {@code hub-public-key.der} every Hub install ships with is a
 * one-time manual export from the SAME key pair (see the generation command in `.env.example`),
 * unrelated to this derivation.
 */
@Lazy
@Service
public class LicenseIssuingService {

    private final PrivateKey privateKey;
    private final PublicKey publicKey;

    public LicenseIssuingService(@Value("${hub.license.private-key}") String privateKeyBase64) {
        try {
            byte[] keyBytes = Base64.getDecoder().decode(privateKeyBase64);
            KeyFactory factory = KeyFactory.getInstance("RSA");
            RSAPrivateCrtKey privateCrtKey =
                    (RSAPrivateCrtKey) factory.generatePrivate(new PKCS8EncodedKeySpec(keyBytes));
            this.privateKey = privateCrtKey;
            this.publicKey = factory.generatePublic(
                    new RSAPublicKeySpec(privateCrtKey.getModulus(), privateCrtKey.getPublicExponent()));
        } catch (GeneralSecurityException | IllegalArgumentException | ClassCastException e) {
            throw new IllegalStateException(
                    "hub.license.private-key inválida: no se pudo cargar como clave RSA PKCS8.", e);
        }
    }

    public String issue(UUID restaurantId) {
        try {
            return LicenseKeyParser.sign(new LicenseKey(restaurantId, Instant.now()), privateKey);
        } catch (GeneralSecurityException | IOException e) {
            throw new IllegalStateException("No se pudo firmar la licencia.", e);
        }
    }

    public PublicKey publicKey() {
        return publicKey;
    }
}
