spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: ember

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:postgresql://localhost:5432/ember
    username: ember
    password: ember
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  data:
    mongodb:
      uri: mongodb://ember:ember@localhost:27017/ember?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ember-secret-key-must-be-at-least-32-characters-long-for-hs256
  expiration-ms: 86400000

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: ember-media

server:
  servlet:
    context-path: /api/v1
