spring.datasource.url=jdbc:postgresql://localhost:5432/ember
spring.datasource.username=ember
spring.datasource.password=ember
spring.data.mongodb.uri=mongodb://ember:ember@localhost:27017/ember?authSource=admin
spring.jpa.hibernate.ddl-auto=update

jwt.secret=33Zx/bcWITide07xKgSHzBXpfMEKICi01oPmHr+jKEiBpBDXH6U6PVjEMc4Iu9yq
jwt.expiration-ms=86400000

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=ember-media
