spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

platform.jwt.secret=${PLATFORM_JWT_SECRET}
platform.jwt.expiration-ms=${PLATFORM_JWT_EXPIRATION_MS:86400000}

minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket=${MINIO_BUCKET:ember-media}
